services:
  - type: web
    name: quiz-backend
    env: python
    region: frankfurt
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      flask db upgrade
      gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quiz-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: MONICA_API_KEY
        value: your-monica-api-key-here

databases:
  - name: quiz-database
    databaseName: quiz_app
    user: quiz_user
    region: frankfurt
    plan: starter
