services:
  - type: web
    name: quiz-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      python -c "from app import init_database; init_database()"
      gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quiz-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
  value: https://quiz-web-app-chi-ten.vercel.app,http://localhost:3000,http://127.0.0.1:3000
      - key: MONICA_API_KEY
        value: your-monica-api-key-here

databases:
  - name: quiz-db
    databaseName: quiz_modular
    user: quiz_user
    region: frankfurt
    plan: free
